# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import icons


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(694, 800)
        MainWindow.setStyleSheet("")
        MainWindow.setFocus()
        MainWindow.setWindowIcon(QtGui.QIcon(":/icons/main_icon.png"))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.search_line = QtWidgets.QLineEdit(self.centralwidget)
        self.search_line.setGeometry(QtCore.QRect(500, 20, 181, 31))
        self.search_line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.search_line.setStyleSheet("font: 12pt \"Constantia\";")
        self.search_line.setAlignment(QtCore.Qt.AlignCenter)
        self.search_line.setObjectName("search_line")
        self.search_line.setPlaceholderText("🔍 Search module")

        self.button_of_pipInstall = QtWidgets.QPushButton(self.centralwidget)
        self.button_of_pipInstall.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.button_of_pipInstall.setObjectName("button_of_pipInstall")
        # create icon for button
        self.button_of_pipInstall.setIcon(QtGui.QIcon(":/icons/download.png"))
        self.button_of_pipInstall.setIconSize(QtCore.QSize(16, 16))

        self.button_of_mylib = QtWidgets.QPushButton(self.centralwidget)
        self.button_of_mylib.setGeometry(QtCore.QRect(150, 20, 121, 31))
        self.button_of_mylib.setObjectName("button_of_mylib")
        self.button_of_mylib.setIcon(QtGui.QIcon(":/icons/library.png"))
        self.button_of_mylib.setIconSize(QtCore.QSize(16, 16))

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 90, 678, 671))
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        # horizontal header
        self.tableWidget.horizontalHeader().setDefaultSectionSize(156)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(10)
        # vertical header
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSectionResizeMode(True)
        self.tableWidget.verticalHeader().setSectionResizeMode(True)
        self.tableWidget.setSelectionMode(False)
        self.tableWidget.verticalHeader().setSectionsClickable(False)
        # visual of column and etc
        self.tableWidget.setHorizontalHeaderLabels(["module", "info", "version", "download"])
        self.tableWidget.horizontalHeader().setSectionsClickable(False)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        # self.tableWidget.horizontalHeader().setSectionResizeMode(2, 10)

        # add tooltip
        self.tableWidget.horizontalHeaderItem(0).setToolTip('''
            <h6 style="background-color: #faebd7; ">Module name. This is a file that contains Python code.</h6> 
        ''')
        self.tableWidget.horizontalHeaderItem(1).setToolTip('''
            <h6 style="background-color: #faebd7; ">Link to module documentation.</h6> 
        ''')
        self.tableWidget.horizontalHeaderItem(2).setToolTip('''
            <h6 style="background-color: #faebd7; ">The current version of the module.</h6> 
        ''')
        self.tableWidget.horizontalHeaderItem(3).setToolTip('''
            <h6 style="background-color: #faebd7; ">Installing a suitable module.</h6> 
        ''')

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyModule Library"))
        self.button_of_pipInstall.setText(_translate("MainWindow", "pip upgrade"))
        self.button_of_mylib.setText(_translate("MainWindow", "My PyModules"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
